version: "3.0"

services:

  wedding-backend: 
    image: wedding-backend
    container_name: wedding-backend
    build: .
    depends_on: 
     - db
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=wedding
    ports:
      - 5000:5000

  db: 
    container_name: db
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wedding
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: